### ISSUE TITLE
sorry about ur depression...

### ISSUE THREAD

**Issue by NullFlex** [HarsaroopDhillon/Titan-Banking-Bot#1]
sike retard i dont care just upload the botnet already

**Comment by Antonio24** [comment]
If the depression went through, I would load the rest of the code and the panel

**Comment by Rakzr** [comment]
What a fag smh

**Comment by Sergomashina** [comment]
let me know if you are interested in work, my contact is jabber supptroi@thesecure.biz

**Comment by HarsaroopDhillon** [comment]
I dont want to cause any harm or hurt my future by actually releasing anything lol... If any actual researcher would actually like to view the full source code I can send it their way via email or by contacting me on xmpp: burnthisbitchtotheground@xmpp.jp
